

```{r}
library(dplyr)
library(magrittr)
library(cytominer)
library(foreach)
library(stringr)
library(readr)
library(iterators)
library(doParallel)
library(reshape2)
library(psych)
library(xtable)
library(ggplot2)
#install.packages("readbulk")
library(readbulk)
#install.packages("devtools")
#devtools::install_github("rstats-db/RSQLite")
library(DBI)


```

## Including Plots

You can also embed plots, for example:


```{r}
# importing csv, metadata file, selected variables
setwd("/Users/habbasi/Desktop/050919_Nathianel_Gray/Scripts")
plate.list <-c('BR00100032', 'BR00100037')
f.path <- NULL


for (p in 1:length(plate.list)) {
  f.path[p]<- paste0("../", plate.list[p], "/", plate.list[p], ".csv")
  metafile[p] <- paste0("../", plate.list[p], "/", plate.list[p], "_Metadata.csv")
  file_varselect[p] <- paste0("../", plate.list[p], "/", plate.list[p],"_normalized_variable_selected.csv")
  variables_imp <- as.data.frame(readr::read_csv(file_varselect[p]), stringsAsFactors =F)
  varlist <- colnames(variables_imp)[which(!str_detect(colnames(variables_imp), "Metadata_"))]

  
# REading files

df <- data.frame(readr::read_csv(f.path[p]), stringsAsFactors =F)
pmeta <- data.frame(readr::read_csv(metafile[p]), stringsAsFactors =F)
metadata <- colnames(df)[which(str_detect(colnames(df), "Metadata_"))]
variables <- colnames(df)[which(!str_detect(colnames(df), "Metadata_"))]
variables_s <- intersect(variables, varlist)

# Merging Metadata information
data <- merge(df, pmeta,
                      by.x = c("Metadata_Plate","Metadata_Well"),
                      by.y = c("Metadata_Plate", "Metadata_Well"))

meta <- colnames(data)[which(str_detect(colnames(data), "Metadata_"))]


# Filtering control cells and sampling number is equal to the no of treatments
dmso <- data %>%
    filter(Metadata_broad_sample == "DMSO") %>%
    dplyr::collect()

set.seed(123)
sample_size <-  112
train_indx <- sample(seq_len(nrow(dmso)), size = sample_size)
dmso <- dmso[train_indx, ]

# Scaling of variables by taking mean and sd of DMSO 
 mn <- apply(dmso %>% select(one_of(variables_s)), 2, function(x) mean(x, na.rm = T))
 sdv <- apply(dmso %>% select(one_of(variables_s)), 2, function(x) sd(x, na.rm = T))
 
data_scaled <- scale(data[, variables_s], center = mn, scale = sdv)
    
data_scaled <- as.data.frame(data_scaled)
df_meta <- data %>% select(meta) %>% dplyr::collect()
profile  <- cbind(df_meta, data_scaled)

readr::write_csv(profile, paste0("../", plate.list[p], "/", plate.list[p], "_normalized_sampled_variable_selected.csv")) 

}




```


